name: arsync_image_cropper
description: Image cropping addon for arsync_image_picker
version: 0.0.4
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/arsync_packages

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  arsync_image_picker: ^0.0.4
  image_cropper: ^9.1.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:

topics:
  - image-cropping
  - image-processing