name: arsync_firebase_errors_handler
description: Firebase error handlers for the Arsync Exception Toolkit
version: 0.0.1
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/arsync_exception_toolkit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arsync_exception_toolkit: ^0.0.4
  firebase_auth_platform_interface: ^7.6.0
  firebase_core_platform_interface: ^5.4.0
  cloud_firestore_platform_interface: ^6.6.4
  cloud_functions_platform_interface: ^5.6.3
  firebase_storage_platform_interface: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0