name: arsync_dio_errors_handler
description: A Dio error handling package that integrates with Arsync Exception Toolkit to provide standardized error handling.
version: 0.0.4
homepage: https://arsyncsolutions.com/
repository: https://github.com/itsatifsiddiqui/arsync_packages

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arsync_exception_toolkit: ^0.0.10
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For local development, uncomment this
# dependency_overrides:
#   arsync_exception_toolkit:
#     path: ../arsync_exception_toolkit
